/**
 * Catppuccin Mocha Theme for Monaco Editor
 * Dark, warm, pastel theme
 */

export const CATPPUCCIN_MOCHA_MONACO = {
  base: 'vs-dark' as const,
  inherit: true,
  rules: [
    { token: 'comment', foreground: '6C7086', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'CBA6F7', fontStyle: 'bold' },
    { token: 'keyword.control', foreground: 'CBA6F7' },
    { token: 'string', foreground: 'A6E3A1' },
    { token: 'number', foreground: 'FAB387' },
    { token: 'function', foreground: '89B4FA' },
    { token: 'identifier.function', foreground: '89B4FA' },
    { token: 'variable', foreground: 'CDD6F4' },
    { token: 'identifier', foreground: 'CDD6F4' },
    { token: 'type', foreground: 'F9E2AF' },
    { token: 'operator', foreground: '94E2D5' },
    { token: 'delimiter', foreground: 'BAC2DE' },
  ],
  colors: {
    'editor.background': '#1E1E2E',
    'editor.foreground': '#CDD6F4',
    'editorLineNumber.foreground': '#6C7086',
    'editorLineNumber.activeForeground': '#CBA6F7',
    'editorCursor.foreground': '#F5E0DC',
    'editorCursor.background': '#1E1E2E',
    'editor.selectionBackground': '#CBA6F740',
    'editor.inactiveSelectionBackground': '#CBA6F720',
    'editor.selectionHighlightBackground': '#CBA6F730',
    'editor.lineHighlightBackground': '#313244',
    'editor.lineHighlightBorder': '#313244',
    'editorGutter.background': '#1E1E2E',
    'minimap.background': '#1E1E2E',
    'scrollbarSlider.background': '#45475A80',
    'scrollbarSlider.hoverBackground': '#45475AB0',
    'scrollbarSlider.activeBackground': '#CBA6F7',
    'editorBracketMatch.background': '#CBA6F740',
    'editorBracketMatch.border': '#CBA6F7',
    'editorWhitespace.foreground': '#6C708640',
    'editorIndentGuide.background': '#6C708620',
    'editorIndentGuide.activeBackground': '#CBA6F760',
    'editorWidget.background': '#313244',
    'editorWidget.border': '#45475A',
    'editorSuggestWidget.background': '#313244',
    'editorSuggestWidget.border': '#45475A',
    'editorSuggestWidget.selectedBackground': '#45475A',
    'editor.findMatchBackground': '#CBA6F760',
    'editor.findMatchHighlightBackground': '#CBA6F730',
    'editorError.foreground': '#F38BA8',
    'editorWarning.foreground': '#FAB387',
    'editorInfo.foreground': '#89B4FA',
  },
};
