/**
 * Catppuccin Latte Theme for Monaco Editor
 * Warm, soothing light theme with pastel colors
 */

export const CATPPUCCIN_LATTE_MONACO = {
  base: 'vs' as const,
  inherit: true,
  rules: [
    { token: 'comment', foreground: '9CA0B0', fontStyle: 'italic' },
    { token: 'keyword', foreground: '8839EF', fontStyle: 'bold' },
    { token: 'keyword.control', foreground: '8839EF' },
    { token: 'string', foreground: '40A02B' },
    { token: 'number', foreground: 'FE640B' },
    { token: 'function', foreground: '1E66F5' },
    { token: 'identifier.function', foreground: '1E66F5' },
    { token: 'variable', foreground: '4C4F69' },
    { token: 'identifier', foreground: '4C4F69' },
    { token: 'type', foreground: 'DF8E1D' },
    { token: 'operator', foreground: '179299' },
    { token: 'delimiter', foreground: '5C5F77' },
  ],
  colors: {
    'editor.background': '#EFF1F5',
    'editor.foreground': '#4C4F69',
    'editorLineNumber.foreground': '#9CA0B0',
    'editorLineNumber.activeForeground': '#8839EF',
    'editorCursor.foreground': '#DC8A78',
    'editorCursor.background': '#EFF1F5',
    'editor.selectionBackground': '#8839EF40',
    'editor.inactiveSelectionBackground': '#8839EF20',
    'editor.selectionHighlightBackground': '#8839EF30',
    'editor.lineHighlightBackground': '#E6E9EF',
    'editor.lineHighlightBorder': '#E6E9EF',
    'editorGutter.background': '#EFF1F5',
    'minimap.background': '#EFF1F5',
    'scrollbarSlider.background': '#CCD0DA80',
    'scrollbarSlider.hoverBackground': '#CCD0DAB0',
    'scrollbarSlider.activeBackground': '#8839EF',
    'editorBracketMatch.background': '#8839EF40',
    'editorBracketMatch.border': '#8839EF',
    'editorWhitespace.foreground': '#9CA0B040',
    'editorIndentGuide.background': '#9CA0B020',
    'editorIndentGuide.activeBackground': '#8839EF60',
    'editorWidget.background': '#E6E9EF',
    'editorWidget.border': '#CCD0DA',
    'editorSuggestWidget.background': '#E6E9EF',
    'editorSuggestWidget.border': '#CCD0DA',
    'editorSuggestWidget.selectedBackground': '#CCD0DA',
    'editor.findMatchBackground': '#8839EF60',
    'editor.findMatchHighlightBackground': '#8839EF30',
    'editorError.foreground': '#D20F39',
    'editorWarning.foreground': '#FE640B',
    'editorInfo.foreground': '#1E66F5',
  },
};
