/**
 * Dracula Theme for Monaco Editor
 * Dark theme with vibrant purple accents
 */

export const DRACULA_MONACO = {
  base: 'vs-dark' as const,
  inherit: true,
  rules: [
    { token: 'comment', foreground: '6272A4', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'FF79C6', fontStyle: 'bold' },
    { token: 'keyword.control', foreground: 'FF79C6' },
    { token: 'string', foreground: 'F1FA8C' },
    { token: 'number', foreground: 'BD93F9' },
    { token: 'function', foreground: '50FA7B' },
    { token: 'identifier.function', foreground: '50FA7B' },
    { token: 'variable', foreground: 'F8F8F2' },
    { token: 'identifier', foreground: 'F8F8F2' },
    { token: 'type', foreground: '8BE9FD' },
    { token: 'operator', foreground: 'FF79C6' },
    { token: 'delimiter', foreground: 'F8F8F2' },
  ],
  colors: {
    'editor.background': '#282A36',
    'editor.foreground': '#F8F8F2',
    'editorLineNumber.foreground': '#6272A4',
    'editorLineNumber.activeForeground': '#FF79C6',
    'editorCursor.foreground': '#F8F8F2',
    'editorCursor.background': '#282A36',
    'editor.selectionBackground': '#44475A',
    'editor.inactiveSelectionBackground': '#44475A80',
    'editor.selectionHighlightBackground': '#44475A60',
    'editor.lineHighlightBackground': '#44475A50',
    'editor.lineHighlightBorder': '#44475A',
    'editorGutter.background': '#282A36',
    'minimap.background': '#282A36',
    'scrollbarSlider.background': '#44475A80',
    'scrollbarSlider.hoverBackground': '#44475AB0',
    'scrollbarSlider.activeBackground': '#FF79C6',
    'editorBracketMatch.background': '#FF79C640',
    'editorBracketMatch.border': '#FF79C6',
    'editorWhitespace.foreground': '#6272A440',
    'editorIndentGuide.background': '#6272A420',
    'editorIndentGuide.activeBackground': '#FF79C660',
    'editorWidget.background': '#44475A',
    'editorWidget.border': '#6272A4',
    'editorSuggestWidget.background': '#44475A',
    'editorSuggestWidget.border': '#6272A4',
    'editorSuggestWidget.selectedBackground': '#6272A4',
    'editor.findMatchBackground': '#FF79C660',
    'editor.findMatchHighlightBackground': '#FF79C630',
    'editorError.foreground': '#FF5555',
    'editorWarning.foreground': '#FFB86C',
    'editorInfo.foreground': '#8BE9FD',
  },
};
