/**
 * GitHub Light Theme for Monaco Editor
 * Clean, professional light theme
 */

export const GITHUB_LIGHT_MONACO = {
  base: 'vs' as const,
  inherit: true,
  rules: [
    { token: 'comment', foreground: '6A737D', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'D73A49', fontStyle: 'bold' },
    { token: 'keyword.control', foreground: 'D73A49' },
    { token: 'string', foreground: '032F62' },
    { token: 'number', foreground: '005CC5' },
    { token: 'function', foreground: '6F42C1' },
    { token: 'identifier.function', foreground: '6F42C1' },
    { token: 'variable', foreground: '24292E' },
    { token: 'identifier', foreground: '24292E' },
    { token: 'type', foreground: '005CC5' },
    { token: 'operator', foreground: 'D73A49' },
    { token: 'delimiter', foreground: '24292E' },
  ],
  colors: {
    'editor.background': '#FFFFFF',
    'editor.foreground': '#24292E',
    'editorLineNumber.foreground': '#D1D5DA',
    'editorLineNumber.activeForeground': '#6F42C1',
    'editorCursor.foreground': '#044289',
    'editorCursor.background': '#FFFFFF',
    'editor.selectionBackground': '#C8E1FF',
    'editor.inactiveSelectionBackground': '#E1E4E8',
    'editor.selectionHighlightBackground': '#F0F3F6',
    'editor.lineHighlightBackground': '#F6F8FA',
    'editor.lineHighlightBorder': '#F6F8FA',
    'editorGutter.background': '#FFFFFF',
    'minimap.background': '#FFFFFF',
    'scrollbarSlider.background': '#D1D5DA80',
    'scrollbarSlider.hoverBackground': '#D1D5DAB0',
    'scrollbarSlider.activeBackground': '#6F42C1',
    'editorBracketMatch.background': '#6F42C140',
    'editorBracketMatch.border': '#6F42C1',
    'editorWhitespace.foreground': '#D1D5DA40',
    'editorIndentGuide.background': '#D1D5DA20',
    'editorIndentGuide.activeBackground': '#6F42C160',
    'editorWidget.background': '#F6F8FA',
    'editorWidget.border': '#E1E4E8',
    'editorSuggestWidget.background': '#F6F8FA',
    'editorSuggestWidget.border': '#E1E4E8',
    'editorSuggestWidget.selectedBackground': '#C8E1FF',
    'editor.findMatchBackground': '#FFD33D60',
    'editor.findMatchHighlightBackground': '#FFD33D30',
    'editorError.foreground': '#D73A49',
    'editorWarning.foreground': '#E36209',
    'editorInfo.foreground': '#005CC5',
  },
};
