/**
 * Nord Theme for Monaco Editor
 * Arctic, north-bluish color palette
 */

export const NORD_MONACO = {
  base: 'vs-dark' as const,
  inherit: true,
  rules: [
    { token: 'comment', foreground: '616E88', fontStyle: 'italic' },
    { token: 'keyword', foreground: '81A1C1', fontStyle: 'bold' },
    { token: 'keyword.control', foreground: '81A1C1' },
    { token: 'string', foreground: 'A3BE8C' },
    { token: 'number', foreground: 'B48EAD' },
    { token: 'function', foreground: '88C0D0' },
    { token: 'identifier.function', foreground: '88C0D0' },
    { token: 'variable', foreground: 'D8DEE9' },
    { token: 'identifier', foreground: 'D8DEE9' },
    { token: 'type', foreground: '8FBCBB' },
    { token: 'operator', foreground: '81A1C1' },
    { token: 'delimiter', foreground: 'ECEFF4' },
  ],
  colors: {
    'editor.background': '#2E3440',
    'editor.foreground': '#D8DEE9',
    'editorLineNumber.foreground': '#4C566A',
    'editorLineNumber.activeForeground': '#88C0D0',
    'editorCursor.foreground': '#D8DEE9',
    'editorCursor.background': '#2E3440',
    'editor.selectionBackground': '#434C5E',
    'editor.inactiveSelectionBackground': '#434C5E80',
    'editor.selectionHighlightBackground': '#434C5E60',
    'editor.lineHighlightBackground': '#3B4252',
    'editor.lineHighlightBorder': '#3B4252',
    'editorGutter.background': '#2E3440',
    'minimap.background': '#2E3440',
    'scrollbarSlider.background': '#4C566A80',
    'scrollbarSlider.hoverBackground': '#4C566AB0',
    'scrollbarSlider.activeBackground': '#88C0D0',
    'editorBracketMatch.background': '#88C0D040',
    'editorBracketMatch.border': '#88C0D0',
    'editorWhitespace.foreground': '#4C566A40',
    'editorIndentGuide.background': '#4C566A20',
    'editorIndentGuide.activeBackground': '#88C0D060',
    'editorWidget.background': '#3B4252',
    'editorWidget.border': '#4C566A',
    'editorSuggestWidget.background': '#3B4252',
    'editorSuggestWidget.border': '#4C566A',
    'editorSuggestWidget.selectedBackground': '#434C5E',
    'editor.findMatchBackground': '#88C0D060',
    'editor.findMatchHighlightBackground': '#88C0D030',
    'editorError.foreground': '#BF616A',
    'editorWarning.foreground': '#EBCB8B',
    'editorInfo.foreground': '#5E81AC',
  },
};
