/**
 * Rosé Pine Dawn Theme for Monaco Editor
 * Elegant, low-contrast light theme
 */

export const ROSE_PINE_DAWN_MONACO = {
  base: 'vs' as const,
  inherit: true,
  rules: [
    { token: 'comment', foreground: '9893A5', fontStyle: 'italic' },
    { token: 'keyword', foreground: '286983', fontStyle: 'bold' },
    { token: 'keyword.control', foreground: '286983' },
    { token: 'string', foreground: '56949F' },
    { token: 'number', foreground: 'EA9D34' },
    { token: 'function', foreground: '907AA9' },
    { token: 'identifier.function', foreground: '907AA9' },
    { token: 'variable', foreground: '575279' },
    { token: 'identifier', foreground: '575279' },
    { token: 'type', foreground: 'D7827E' },
    { token: 'operator', foreground: '286983' },
    { token: 'delimiter', foreground: '797593' },
  ],
  colors: {
    'editor.background': '#FAF4ED',
    'editor.foreground': '#575279',
    'editorLineNumber.foreground': '#CECACD',
    'editorLineNumber.activeForeground': '#907AA9',
    'editorCursor.foreground': '#575279',
    'editorCursor.background': '#FAF4ED',
    'editor.selectionBackground': '#907AA940',
    'editor.inactiveSelectionBackground': '#907AA920',
    'editor.selectionHighlightBackground': '#907AA930',
    'editor.lineHighlightBackground': '#F2E9E1',
    'editor.lineHighlightBorder': '#F2E9E1',
    'editorGutter.background': '#FAF4ED',
    'minimap.background': '#FAF4ED',
    'scrollbarSlider.background': '#CECACD80',
    'scrollbarSlider.hoverBackground': '#CECACDB0',
    'scrollbarSlider.activeBackground': '#907AA9',
    'editorBracketMatch.background': '#907AA940',
    'editorBracketMatch.border': '#907AA9',
    'editorWhitespace.foreground': '#CECACD40',
    'editorIndentGuide.background': '#CECACD20',
    'editorIndentGuide.activeBackground': '#907AA960',
    'editorWidget.background': '#F2E9E1',
    'editorWidget.border': '#CECACD',
    'editorSuggestWidget.background': '#F2E9E1',
    'editorSuggestWidget.border': '#CECACD',
    'editorSuggestWidget.selectedBackground': '#CECACD',
    'editor.findMatchBackground': '#907AA960',
    'editor.findMatchHighlightBackground': '#907AA930',
    'editorError.foreground': '#B4637A',
    'editorWarning.foreground': '#EA9D34',
    'editorInfo.foreground': '#286983',
  },
};
