/**
 * Tokyo Night Theme for Monaco Editor
 * Dark theme inspired by Tokyo's neon lights
 */

export const TOKYO_NIGHT_MONACO = {
  base: 'vs-dark' as const,
  inherit: true,
  rules: [
    { token: 'comment', foreground: '565F89', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'BB9AF7', fontStyle: 'bold' },
    { token: 'keyword.control', foreground: 'BB9AF7' },
    { token: 'string', foreground: '9ECE6A' },
    { token: 'number', foreground: 'FF9E64' },
    { token: 'function', foreground: '7AA2F7' },
    { token: 'identifier.function', foreground: '7AA2F7' },
    { token: 'variable', foreground: 'C0CAF5' },
    { token: 'identifier', foreground: 'C0CAF5' },
    { token: 'type', foreground: '2AC3DE' },
    { token: 'operator', foreground: '89DDFF' },
    { token: 'delimiter', foreground: 'A9B1D6' },
  ],
  colors: {
    'editor.background': '#1A1B26',
    'editor.foreground': '#C0CAF5',
    'editorLineNumber.foreground': '#3B4261',
    'editorLineNumber.activeForeground': '#7AA2F7',
    'editorCursor.foreground': '#C0CAF5',
    'editorCursor.background': '#1A1B26',
    'editor.selectionBackground': '#33467C',
    'editor.inactiveSelectionBackground': '#33467C80',
    'editor.selectionHighlightBackground': '#33467C60',
    'editor.lineHighlightBackground': '#1F2335',
    'editor.lineHighlightBorder': '#1F2335',
    'editorGutter.background': '#1A1B26',
    'minimap.background': '#1A1B26',
    'scrollbarSlider.background': '#3B426180',
    'scrollbarSlider.hoverBackground': '#3B4261B0',
    'scrollbarSlider.activeBackground': '#7AA2F7',
    'editorBracketMatch.background': '#7AA2F740',
    'editorBracketMatch.border': '#7AA2F7',
    'editorWhitespace.foreground': '#3B426140',
    'editorIndentGuide.background': '#3B426120',
    'editorIndentGuide.activeBackground': '#7AA2F760',
    'editorWidget.background': '#1F2335',
    'editorWidget.border': '#3B4261',
    'editorSuggestWidget.background': '#1F2335',
    'editorSuggestWidget.border': '#3B4261',
    'editorSuggestWidget.selectedBackground': '#33467C',
    'editor.findMatchBackground': '#7AA2F760',
    'editor.findMatchHighlightBackground': '#7AA2F730',
    'editorError.foreground': '#F7768E',
    'editorWarning.foreground': '#E0AF68',
    'editorInfo.foreground': '#7AA2F7',
  },
};
